// flow-typed signature: d31af997c1193e7997f851078b609d4f
// flow-typed version: <<STUB>>/bedrock_vgit://github.com/Sendoushi/bedrock.git#0.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bedrock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bedrock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bedrock/src/actions' {
  declare module.exports: any;
}

declare module 'bedrock/src/actions/request' {
  declare module.exports: any;
}

declare module 'bedrock/src/component' {
  declare module.exports: any;
}

declare module 'bedrock/src/mailbox' {
  declare module.exports: any;
}

declare module 'bedrock/src/reducers/breadcrumb' {
  declare module.exports: any;
}

declare module 'bedrock/src/reducers/err' {
  declare module.exports: any;
}

declare module 'bedrock/src/reducers/loading' {
  declare module.exports: any;
}

declare module 'bedrock/src/router' {
  declare module.exports: any;
}

declare module 'bedrock/src/state' {
  declare module.exports: any;
}

declare module 'bedrock/src/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bedrock/src/actions.js' {
  declare module.exports: $Exports<'bedrock/src/actions'>;
}
declare module 'bedrock/src/actions/request.js' {
  declare module.exports: $Exports<'bedrock/src/actions/request'>;
}
declare module 'bedrock/src/component.js' {
  declare module.exports: $Exports<'bedrock/src/component'>;
}
declare module 'bedrock/src/mailbox.js' {
  declare module.exports: $Exports<'bedrock/src/mailbox'>;
}
declare module 'bedrock/src/reducers/breadcrumb.js' {
  declare module.exports: $Exports<'bedrock/src/reducers/breadcrumb'>;
}
declare module 'bedrock/src/reducers/err.js' {
  declare module.exports: $Exports<'bedrock/src/reducers/err'>;
}
declare module 'bedrock/src/reducers/loading.js' {
  declare module.exports: $Exports<'bedrock/src/reducers/loading'>;
}
declare module 'bedrock/src/router.js' {
  declare module.exports: $Exports<'bedrock/src/router'>;
}
declare module 'bedrock/src/state.js' {
  declare module.exports: $Exports<'bedrock/src/state'>;
}
declare module 'bedrock/src/store.js' {
  declare module.exports: $Exports<'bedrock/src/store'>;
}
