// flow-typed signature: 59ce26dd03a7b3da8b805974b11cb2c7
// flow-typed version: <<STUB>>/dot_v^1.0.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dot/benchmarks/compileBench' {
  declare module.exports: any;
}

declare module 'dot/benchmarks/jslitmus' {
  declare module.exports: any;
}

declare module 'dot/benchmarks/templatesBench' {
  declare module.exports: any;
}

declare module 'dot/benchmarks/templating/doT' {
  declare module.exports: any;
}

declare module 'dot/benchmarks/templating/doU' {
  declare module.exports: any;
}

declare module 'dot/doT' {
  declare module.exports: any;
}

declare module 'dot/doT.min' {
  declare module.exports: any;
}

declare module 'dot/doU' {
  declare module.exports: any;
}

declare module 'dot/examples/customdoT' {
  declare module.exports: any;
}

declare module 'dot/examples/express/index' {
  declare module.exports: any;
}

declare module 'dot/examples/express/lib/app' {
  declare module.exports: any;
}

declare module 'dot/examples/express/lib/render/index' {
  declare module.exports: any;
}

declare module 'dot/examples/withdoT' {
  declare module.exports: any;
}

declare module 'dot/test/conditionals.test' {
  declare module.exports: any;
}

declare module 'dot/test/defines.test' {
  declare module.exports: any;
}

declare module 'dot/test/dot.test' {
  declare module.exports: any;
}

declare module 'dot/test/iteration.test' {
  declare module.exports: any;
}

declare module 'dot/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dot/benchmarks/compileBench.js' {
  declare module.exports: $Exports<'dot/benchmarks/compileBench'>;
}
declare module 'dot/benchmarks/jslitmus.js' {
  declare module.exports: $Exports<'dot/benchmarks/jslitmus'>;
}
declare module 'dot/benchmarks/templatesBench.js' {
  declare module.exports: $Exports<'dot/benchmarks/templatesBench'>;
}
declare module 'dot/benchmarks/templating/doT.js' {
  declare module.exports: $Exports<'dot/benchmarks/templating/doT'>;
}
declare module 'dot/benchmarks/templating/doU.js' {
  declare module.exports: $Exports<'dot/benchmarks/templating/doU'>;
}
declare module 'dot/doT.js' {
  declare module.exports: $Exports<'dot/doT'>;
}
declare module 'dot/doT.min.js' {
  declare module.exports: $Exports<'dot/doT.min'>;
}
declare module 'dot/doU.js' {
  declare module.exports: $Exports<'dot/doU'>;
}
declare module 'dot/examples/customdoT.js' {
  declare module.exports: $Exports<'dot/examples/customdoT'>;
}
declare module 'dot/examples/express/index.js' {
  declare module.exports: $Exports<'dot/examples/express/index'>;
}
declare module 'dot/examples/express/lib/app.js' {
  declare module.exports: $Exports<'dot/examples/express/lib/app'>;
}
declare module 'dot/examples/express/lib/render/index.js' {
  declare module.exports: $Exports<'dot/examples/express/lib/render/index'>;
}
declare module 'dot/examples/withdoT.js' {
  declare module.exports: $Exports<'dot/examples/withdoT'>;
}
declare module 'dot/index' {
  declare module.exports: $Exports<'dot'>;
}
declare module 'dot/index.js' {
  declare module.exports: $Exports<'dot'>;
}
declare module 'dot/test/conditionals.test.js' {
  declare module.exports: $Exports<'dot/test/conditionals.test'>;
}
declare module 'dot/test/defines.test.js' {
  declare module.exports: $Exports<'dot/test/defines.test'>;
}
declare module 'dot/test/dot.test.js' {
  declare module.exports: $Exports<'dot/test/dot.test'>;
}
declare module 'dot/test/iteration.test.js' {
  declare module.exports: $Exports<'dot/test/iteration.test'>;
}
declare module 'dot/test/util.js' {
  declare module.exports: $Exports<'dot/test/util'>;
}
