// flow-typed signature: d313494f16f4e0813d53334cfa549993
// flow-typed version: <<STUB>>/stylelint-scss_v^1.3.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-scss/dist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-function-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-no-partial-extension/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/at-mixin-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/dollar-variable-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-inline/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/operator-no-unspaced/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/partial-no-import/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/percent-placeholder-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/atRuleParamIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/declarationValueIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/findCommentsInRaws' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/hasInterpolatingAmpersand' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isInlineComment' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isStandardRule' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isStandardSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/namespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/optionsHaveException' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/optionsHaveIgnored' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/parseSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/sassValueParser/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/dist/utils/whitespaceChecker' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-extend-no-missing-placeholder/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-function-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-import-no-partial-extension/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-import-no-partial-leading-underscore/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-import-partial-extension-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-import-partial-extension-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-mixin-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-mixin-no-argumentless-call-parentheses/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/at-mixin-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/dollar-variable-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/dollar-variable-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/dollar-variable-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/dollar-variable-no-missing-interpolation/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/dollar-variable-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/double-slash-comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/double-slash-comment-inline/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/double-slash-comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/media-feature-value-dollar-variable/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/operator-no-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/operator-no-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/operator-no-unspaced/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/partial-no-import/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/percent-placeholder-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/rules/selector-no-redundant-nesting-selector/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/atRuleParamIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/declarationValueIndex' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/findCommentsInRaws' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/hasInterpolatingAmpersand' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/isInlineComment' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/isStandardRule' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/isStandardSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/namespace' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/optionsHaveException' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/optionsHaveIgnored' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/parseSelector' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/sassValueParser/index' {
  declare module.exports: any;
}

declare module 'stylelint-scss/src/utils/whitespaceChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-scss/dist/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-extend-no-missing-placeholder/index'>;
}
declare module 'stylelint-scss/dist/rules/at-function-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-function-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-no-partial-extension/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-no-partial-extension/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-no-partial-leading-underscore/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-partial-extension-blacklist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-import-partial-extension-whitelist/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-no-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/dist/rules/at-mixin-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/at-mixin-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-space-after/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-colon-space-before/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index'>;
}
declare module 'stylelint-scss/dist/rules/dollar-variable-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/dollar-variable-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-empty-line-before/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-inline/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-inline/index'>;
}
declare module 'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/double-slash-comment-whitespace-inside/index'>;
}
declare module 'stylelint-scss/dist/rules/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/index'>;
}
declare module 'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/media-feature-value-dollar-variable/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-newline-after/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-newline-before/index'>;
}
declare module 'stylelint-scss/dist/rules/operator-no-unspaced/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/operator-no-unspaced/index'>;
}
declare module 'stylelint-scss/dist/rules/partial-no-import/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/partial-no-import/index'>;
}
declare module 'stylelint-scss/dist/rules/percent-placeholder-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/percent-placeholder-pattern/index'>;
}
declare module 'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/rules/selector-no-redundant-nesting-selector/index'>;
}
declare module 'stylelint-scss/dist/utils/atRuleParamIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/atRuleParamIndex'>;
}
declare module 'stylelint-scss/dist/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/configurationError'>;
}
declare module 'stylelint-scss/dist/utils/declarationValueIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/declarationValueIndex'>;
}
declare module 'stylelint-scss/dist/utils/findCommentsInRaws.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/findCommentsInRaws'>;
}
declare module 'stylelint-scss/dist/utils/hasInterpolatingAmpersand.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/hasInterpolatingAmpersand'>;
}
declare module 'stylelint-scss/dist/utils/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/index'>;
}
declare module 'stylelint-scss/dist/utils/isInlineComment.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isInlineComment'>;
}
declare module 'stylelint-scss/dist/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isSingleLineString'>;
}
declare module 'stylelint-scss/dist/utils/isStandardRule.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isStandardRule'>;
}
declare module 'stylelint-scss/dist/utils/isStandardSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isStandardSelector'>;
}
declare module 'stylelint-scss/dist/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/isWhitespace'>;
}
declare module 'stylelint-scss/dist/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/namespace'>;
}
declare module 'stylelint-scss/dist/utils/optionsHaveException.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/optionsHaveException'>;
}
declare module 'stylelint-scss/dist/utils/optionsHaveIgnored.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/optionsHaveIgnored'>;
}
declare module 'stylelint-scss/dist/utils/parseSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/parseSelector'>;
}
declare module 'stylelint-scss/dist/utils/sassValueParser/index.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/sassValueParser/index'>;
}
declare module 'stylelint-scss/dist/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint-scss/dist/utils/whitespaceChecker'>;
}
declare module 'stylelint-scss/src/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/index'>;
}
declare module 'stylelint-scss/src/rules/at-extend-no-missing-placeholder/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-extend-no-missing-placeholder/index'>;
}
declare module 'stylelint-scss/src/rules/at-function-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-function-pattern/index'>;
}
declare module 'stylelint-scss/src/rules/at-import-no-partial-extension/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-import-no-partial-extension/index'>;
}
declare module 'stylelint-scss/src/rules/at-import-no-partial-leading-underscore/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-import-no-partial-leading-underscore/index'>;
}
declare module 'stylelint-scss/src/rules/at-import-partial-extension-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-import-partial-extension-blacklist/index'>;
}
declare module 'stylelint-scss/src/rules/at-import-partial-extension-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-import-partial-extension-whitelist/index'>;
}
declare module 'stylelint-scss/src/rules/at-mixin-argumentless-call-parentheses/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-mixin-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/src/rules/at-mixin-no-argumentless-call-parentheses/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-mixin-no-argumentless-call-parentheses/index'>;
}
declare module 'stylelint-scss/src/rules/at-mixin-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/at-mixin-pattern/index'>;
}
declare module 'stylelint-scss/src/rules/dollar-variable-colon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/dollar-variable-colon-newline-after/index'>;
}
declare module 'stylelint-scss/src/rules/dollar-variable-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/dollar-variable-colon-space-after/index'>;
}
declare module 'stylelint-scss/src/rules/dollar-variable-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/dollar-variable-colon-space-before/index'>;
}
declare module 'stylelint-scss/src/rules/dollar-variable-no-missing-interpolation/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/dollar-variable-no-missing-interpolation/index'>;
}
declare module 'stylelint-scss/src/rules/dollar-variable-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/dollar-variable-pattern/index'>;
}
declare module 'stylelint-scss/src/rules/double-slash-comment-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/double-slash-comment-empty-line-before/index'>;
}
declare module 'stylelint-scss/src/rules/double-slash-comment-inline/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/double-slash-comment-inline/index'>;
}
declare module 'stylelint-scss/src/rules/double-slash-comment-whitespace-inside/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/double-slash-comment-whitespace-inside/index'>;
}
declare module 'stylelint-scss/src/rules/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/index'>;
}
declare module 'stylelint-scss/src/rules/media-feature-value-dollar-variable/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/media-feature-value-dollar-variable/index'>;
}
declare module 'stylelint-scss/src/rules/operator-no-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/operator-no-newline-after/index'>;
}
declare module 'stylelint-scss/src/rules/operator-no-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/operator-no-newline-before/index'>;
}
declare module 'stylelint-scss/src/rules/operator-no-unspaced/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/operator-no-unspaced/index'>;
}
declare module 'stylelint-scss/src/rules/partial-no-import/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/partial-no-import/index'>;
}
declare module 'stylelint-scss/src/rules/percent-placeholder-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/percent-placeholder-pattern/index'>;
}
declare module 'stylelint-scss/src/rules/selector-no-redundant-nesting-selector/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/rules/selector-no-redundant-nesting-selector/index'>;
}
declare module 'stylelint-scss/src/utils/atRuleParamIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/atRuleParamIndex'>;
}
declare module 'stylelint-scss/src/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/configurationError'>;
}
declare module 'stylelint-scss/src/utils/declarationValueIndex.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/declarationValueIndex'>;
}
declare module 'stylelint-scss/src/utils/findCommentsInRaws.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/findCommentsInRaws'>;
}
declare module 'stylelint-scss/src/utils/hasInterpolatingAmpersand.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/hasInterpolatingAmpersand'>;
}
declare module 'stylelint-scss/src/utils/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/index'>;
}
declare module 'stylelint-scss/src/utils/isInlineComment.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/isInlineComment'>;
}
declare module 'stylelint-scss/src/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/isSingleLineString'>;
}
declare module 'stylelint-scss/src/utils/isStandardRule.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/isStandardRule'>;
}
declare module 'stylelint-scss/src/utils/isStandardSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/isStandardSelector'>;
}
declare module 'stylelint-scss/src/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/isWhitespace'>;
}
declare module 'stylelint-scss/src/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/namespace'>;
}
declare module 'stylelint-scss/src/utils/optionsHaveException.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/optionsHaveException'>;
}
declare module 'stylelint-scss/src/utils/optionsHaveIgnored.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/optionsHaveIgnored'>;
}
declare module 'stylelint-scss/src/utils/parseSelector.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/parseSelector'>;
}
declare module 'stylelint-scss/src/utils/sassValueParser/index.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/sassValueParser/index'>;
}
declare module 'stylelint-scss/src/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint-scss/src/utils/whitespaceChecker'>;
}
